"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, clearSession, Patient } from "@/lib/api";

export default function SecretariatPage() {
  const router = useRouter(); const [patients, setPatients] = useState<Patient[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (localStorage.getItem("medical_role") !== "secretary") router.replace("/connexion"); }, [router]);
  async function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const term = String(new FormData(event.currentTarget).get("term")); try { setPatients(await api<Patient[]>(`/patients/search?term=${encodeURIComponent(term)}`)); } catch (err) { setError(err instanceof Error ? err.message : "Recherche impossible."); } }
  async function updatePatient(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api(`/patients/${data.get("patientId")}/administrative`, { method: "PATCH", body: JSON.stringify({ national_id: data.get("nationalId") || null, address: data.get("address") || null }) }); setMessage("Données administratives enregistrées."); } catch (err) { setError(err instanceof Error ? err.message : "Mise à jour impossible."); } }
  async function appointment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await api("/appointments/secretariat", { method: "POST", body: JSON.stringify({ patient_id: data.get("patientId"), doctor_id: data.get("doctorId"), scheduled_at: new Date(String(data.get("scheduledAt"))).toISOString(), reason: data.get("reason") || null }) }); setMessage("Rendez-vous créé."); event.currentTarget.reset(); } catch (err) { setError(err instanceof Error ? err.message : "Création impossible."); } }
  return <main className="contentPage"><header className="simpleHeader"><a className="brand" href="/secretariat">MedLink</a><button className="secondaryButton" onClick={() => { clearSession(); router.push("/connexion"); }}>Déconnexion</button></header><section className="pageHeading"><p className="eyebrow">SECRÉTARIAT MÉDICAL</p><h1>Accueil des patients</h1><p>Le CIN est géré ici, jamais au moment de l’inscription patient.</p></section>{error && <p className="formError">{error}</p>}{message && <p className="successText">{message}</p>}<section className="recordGrid"><article className="listCard"><h2>Rechercher un patient</h2><form onSubmit={search}><label>CIN ou nom</label><input name="term" minLength={2} required /><button className="button authButton">Rechercher</button></form>{patients.map((patient) => <div className="recordItem" key={patient.id}><strong>{patient.first_name} {patient.last_name}</strong><p>Identifiant : {patient.id}</p><small>CIN : {patient.national_id || "non renseigné"}</small></div>)}</article><article className="listCard"><h2>Compléter le dossier</h2><form onSubmit={updatePatient}><label>Identifiant patient</label><input name="patientId" required /><label>CIN / Carte nationale</label><input name="nationalId" placeholder="Ex. AB123456" /><label>Adresse</label><input name="address" /><button className="button authButton">Enregistrer</button></form></article><article className="listCard"><h2>Créer un rendez-vous</h2><form onSubmit={appointment}><label>Identifiant patient</label><input name="patientId" required /><label>Identifiant médecin</label><input name="doctorId" required /><label>Date et heure</label><input name="scheduledAt" type="datetime-local" required /><label>Motif</label><input name="reason" /><button className="button authButton">Programmer</button></form></article></section></main>;
}
